Exercicios/Exemplo-MVC02-master/ExemploMVC02/Models/Recrutadora.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ExemploMVC02.Models
{
    public class Recrutadora
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Nome não deve ser vazio!")]
        [MinLength(7,ErrorMessage = "Nome deve conter no minimo 7")]
        [MaxLength(100,ErrorMessage = "Nome deve ter no maximo 100")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "CPF não deve ser vazio")]
        [MinLength(11, ErrorMessage="CPF deve conter somente 11 caracteres")]
        public string CPF { get; set; }

        [Required(ErrorMessage="Tempo de empresa deve ser preenchido")]
        [Range(0,6, ErrorMessage="Pessoa deve ter  entre 0 a 6 anos de empresa")]
        public byte TempoEmpresa { get; set; }

        [Required(ErrorMessage="Salário deve ser preenchido")]
        [Range(1200.00, 100000.00, ErrorMessage="Salário deve estar entre R$ 1.200,00 á R$100.000,00")]
        public decimal Salario { get; set; }

    }
}

Exercicios/Exemplo-MVC02-master/ExemploMVC02/Controllers/RecrutadoraController.cs
using ExemploMVC02.Database;
using ExemploMVC02.Models;
using ExemploMVC02.Repositorio;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExemploMVC02.Controllers
{
    public class RecrutadoraController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            List<Recrutadora> recrutadoras = new RecrutadoraRepository().ObterTodos();
            ViewBag.Recrutadoras = recrutadoras;
            ViewBag.TituloPagina = "Recrutadoras";
            return View();
        }

        [HttpGet]
        public ActionResult Cadastro()
        {
            ViewBag.TituloPagina = "Recrutadoras - Cadastro";
            ViewBag.Recrutadora = new Recrutadora();
            return View();
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            Recrutadora recrutadora = new RecrutadoraRepository().ObterPeloId(id);
            ViewBag.Recrutadora = recrutadora;
            return View();
        }

        [HttpPost]
        public ActionResult Store(Recrutadora recrutadora)
        {
            if (ModelState.IsValid)
            {
                recrutadora.CPF = recrutadora.CPF.Replace(".", "").Replace("-", "");
                int identificador = new RecrutadoraRepository().Cadastrar(recrutadora);
                return RedirectToAction("Editar", new { id = identificador });
            }
            ViewBag.Recrutadora = recrutadora;
            return View("Cadastro");

        }

        [HttpPost]
        public ActionResult Update(Recrutadora recrutadora)
        {
            bool alterado = new RecrutadoraRepository().Alterar(recrutadora);
            return null;
        }

        [HttpGet]
        public ActionResult Excluir(int id)
        {
            bool apagado = new RecrutadoraRepository().Excluir(id);
            return null;
        }
    }
}

Exercicios/Exemplo-MVC02-master/ExemploMVC02/Views/Recrutadora/Cadastro.cshtml
@{
    Layout = "~/Views/shared/Master.cshtml";
}


<div>
    <form action="/Recrutadora/Store" method="post" onsubmit="validarFormulario()">
        <div class="form-group" id="div-campo-nome">
            <label for="campo-nome">Nome<span class="text-danger font-weight-bold">*</span></label>
            <input type="text" class="form-control" name="Recrutadora.Nome" id="campo-nome" required="required" onfocusout="validarCampoNome()" value="@ViewBag.Recrutadora.Nome"/>
            @Html.ValidationMessage("Recrutadora.Nome", new { @class = "text-danger" })
        </div>
        <div>
            <label for="campo-cpf">CPF<span class="text-danger font-weight-bold">*</span></label>
            <input type="text" class="form-control" name="Recrutadora.CPF" id="campo-cpf" required="required" value="@ViewBag.Recrutadora.CPF"/>
            @Html.ValidationMessage("Recrutadora.CPF", new { @class = "text-danger" })
        </div>
        <div>
            <label for="campo-salario">Salário</label>
            <input type="text" class="form-control" name="Recrutadora.Salario" id="campo-salario" required="required" value="@ViewBag.Recrutadora.Salario"/>
            @Html.ValidationMessage("Recrutadora.Salario", new { @class = "text-danger" })
        </div>
        <div>
            <label for="campo-tempo-empresa">Tempo Empresa</label>
            <select id="campo-tempo-empresa" name="Recrutadora.TempoEmpresa" class="form-control">
                <option value="0">0 ano</option>
                <option value="1">1 ano</option>
                <option value="2">2 ano</option>
                <option value="3">3 ano</option>
                <option value="4">4 ano</option>
                <option value="5">5 ano</option>
                <option value="6">6 ano</option>
            </select>
            @Html.ValidationMessage("Recrutadora.TempoEmpresa", new { @class = "text-danger" })
        </div>
        <button type="submit" class="btn btn-outline-success"><i class="fa fa-save"></i> Salvar</button>
    </form>
</div>

Exercicios/Exemplo-MVC02-master/ExemploMVC02/Views/Recrutadora/Editar.cshtml
@{
    Layout = "~/Views/shared/Master.cshtml";
}
<div class="row mt-3">
    <div class="col-md-12">
        <h5 class="text-primary text-center">Editar Recrutadora</h5>
    </div>
</div>
<div>
    <form action="/Recrutadora/Update" method="post">

        <input type="hidden" name="Recrutadora.id" value="@ViewBag.Recrutadora.Id" class="form-control" />
        <div>
            <label for="campo-nome">Nome</label>
            <input type="text" name="Recrutadora.Nome" id="campo-nome" value="@ViewBag.Recrutadora.Nome" required="required" />
            @Html.ValidationMessage("Recrutadora.Nome", new { @class = "text-danger" })
        </div>
        <div>
            <label for="campo-cpf">CPF</label>
            <input type="text" name="Recrutadora.CPF" id="campo-cpf" value="@ViewBag.Recrutadora.CPF" required="required" />
            @Html.ValidationMessage("Recrutadora.CPF", new { @class = "text-danger" })
        </div>
        <div>
            <label for="campo-salario">Salário</label>
            <input type="text" name="Recrutadora.Salario" id="campo-salario" value="@ViewBag.Recrutadora.Salario" required="required" />
            @Html.ValidationMessage("Recrutadora.Salario", new { @class = "text-danger" })
        </div>
        <div>
            <label for="campo-tempo-empresa">Tempo Empresa</label>
            <select id="campo-tempo-empresa" name="Recrutadora.TempoEmpresa ">

                @for (int i = 0; i < 7; i++)
                {
                    if (i == @ViewBag.Recrutadora.TempoEmpresa)
                    {
                        <option value="@i" selected="selected">@i anos</option>
                    }
                    else
                    {

                        <option value="@i" class="dropdown-item">@i anos</option>
                    }
                }
            </select>
            @Html.ValidationMessage("Recrutadora.TempoEmpresa", new { @class = "text-danger" })
        </div>

        <div class="row">
            <div class="col-md-12">
                <button type="submit" class="btn btn-outline-success float-right" value="Salvar"><i class="fa fa-save">Salvar</i></button>
            </div>
        </div>

    </form>
</div>

Exercicios/Exemplo-MVC02-master/ExemploMVC02/Views/Recrutadora/Index.cshtml
@{
    Layout = "~/Views/shared/Master.cshtml";
}


@Html.ActionLink("Novo Recrutadora", "Cadastro", "Recrutadora", new { @class = "btn btn-outline-light float-right mb-2 mt-2" })

<div class="m-3 ml-3">
    <table>
        <thead class="table table-striped table-hover">
            <tr class="bg-primary text-white">
                <th>Código</th>
                <th>Nome</th>
                <th>CPF</th>
                <th>Ação</th>
            </tr>
        </thead>
        <tbody>
            @foreach (ExemploMVC02.Models.Recrutadora recrutadora in @ViewBag.Recrutadoras)
            {
                <tr>
                    <td>@recrutadora.Id</td>
                    <td>@recrutadora.Nome</td>
                    <td>@recrutadora.CPF</td>
                    <td>
                        <a href="/Recrutadora/Editar?id=@recrutadora.Id" class="btn btn-outline-success"><i class="fas fa-edit"></i>Editar</a>
                        <a href="/Recrutadora/Excluir?id=@recrutadora.Id" class="btn btn-outline-danger"><i class="fas fa-trash"></i>Excluir</a>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <th>Código</th>
                <th>Nome</th>
                <th>CPF</th>
                <th>Ação</th>
            </tr>
        </tfoot>
    </table>
</div>

Exercicios/Exemplo-MVC02-master/ExemploMVC02/Views/shared/Master.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.TituloPagina</title>
    <link rel="stylesheet" href="~/Content/bootstrap/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/all.css" />
    <script src="~/Scripts/Recrutadora/cadastro.js"></script>
</head>
<body>
    <div class="container-fluid">
        @RenderBody() 

    </div>
</body>
</html>